app/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from app import db
from app.forms import UserCreateForm, UserLoginForm
from app.models import User
import functools

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('Username is already taken.')
    return render_template('auth/signup.html', form=form)
    
@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "User information does not exist."
        elif not check_password_hash(user.password, form.password.data):
            error = "The password you entered is incorrect."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            _next = request.args.get('next', '')
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)
    
@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)
        
@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))
    
def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.login', next=_next))
        return view(*args, **kwargs)
    return wrapped_view

app/views/data_views.py
from flask import Blueprint, Flask, jsonify, request,render_template,make_response, redirect,url_for, Response
import Adafruit_DHT
import time
from app.camera import Camera
from app.views.auth_views import login_required
import RPi.GPIO as GPIO


GPIO.setmode(GPIO.BCM)

pin = 18	
pin1 = 20
pin2 = 21
EN1 = 16
pin3 = 19
pin4 = 26
EN2 = 13

GPIO.setup(pin1, GPIO.OUT)
GPIO.setup(pin2, GPIO.OUT)
GPIO.setup(EN1, GPIO.OUT)
GPIO.setup(pin3, GPIO.OUT)
GPIO.setup(pin4, GPIO.OUT)
GPIO.setup(EN2, GPIO.OUT)

sensor = Adafruit_DHT.DHT11
#sensor = adafruit_dht.DHT11(board.D18)
bp = Blueprint('data', __name__, url_prefix='/data')

@bp.route('/camera/')
@login_required
def get_camera():
	get_time=time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
	return render_template("data/get_cam.html", cur_time=get_time)

def gen(camera):
   while True:
       frame = camera.get_frame()
       yield (b'--frame\r\n'
              b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')
    
@bp.route('/humid/')
@login_required
def get_data():
	humidity, temperature = Adafruit_DHT.read_retry(sensor, pin)
	if humidity is not None and temperature is not None :
	    print('Temp = %0.1f*C Humid = %0.1f%' % (temperature, humidity))
	#humidity = sensor.humidity
	return render_template("data/get_data.html", hum=humidity)
    
@bp.route('/video_feed')
@login_required
def video_feed():
   return Response(gen(Camera()), mimetype='multipart/x-mixed-replace; boundary=frame')
   


def motor1():
    GPIO.output(pin1, GPIO.HIGH)
    GPIO.output(pin2, GPIO.LOW)
    GPIO.output(EN1, GPIO.HIGH)

def motor2():
    GPIO.output(pin3, GPIO.HIGH)
    GPIO.output(pin4, GPIO.LOW)
    GPIO.output(EN2, GPIO.HIGH)

def motor1Stop():
    GPIO.output(pin1, GPIO.LOW)
    GPIO.output(pin2, GPIO.LOW)
    GPIO.output(EN1, GPIO.LOW)
    #GPIO.cleanup()
		
def motor2Stop():
    GPIO.output(pin3, GPIO.LOW)
    GPIO.output(pin4, GPIO.LOW)
    GPIO.output(EN2, GPIO.LOW)
    #GPIO.cleanup()
		   
@bp.route('/motor')
@login_required
def motorhome(): 
   return render_template("data/motor_control.html")

@bp.route('/motor', methods = ['POST'])
@login_required
def state():
    state = request.form['motor']
    
    if(state == 'motor_on'):
       motor1()
       return motorhome()
    elif(state == 'motor_off'):
       motor1Stop()  
       return motorhome()
    elif(state == 'fan_on'):     
       motor2()
       return motorhome()
    elif(state == 'fan_off'):  
       motor2Stop()
       return motorhome()

app/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <!-- pybo CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>HAMA</title>
</head>
<body>
<!-- nav -->
{% include "navbar.html" %}
<!-- basic content Start -->
{% block content %}
{% endblock %}
<!-- basic content End -->
<!-- Bootstrap JS -->
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
<!-- JavaScript Start -->
{% block script %}
{% endblock %}
<!-- JavaScript End -->
</body>
</html>

app/templates/form_errors.html
<!-- field error -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash error -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

app/templates/navbar.html
<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">HAMA</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
             {% if g.user %}
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (Logout)</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('data.get_data') }}">Humidity</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('data.get_camera') }}">Streaming</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('data.motorhome') }}">Control</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">Sign up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('data.get_data') }}">Humidity</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('data.get_camera') }}">Streaming</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('data.motorhome') }}">Control</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>